# Generated by Django 4.0.4 on 2022-08-11 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=200)),
                ('user_phone_number', models.IntegerField()),
                ('user_device_id', models.CharField(max_length=200)),
                ('lat', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('user_address', models.CharField(max_length=200)),
                ('creation_date', models.DateTimeField(default=None)),
                ('email_status', models.BooleanField(default=False)),
                ('email_score', models.IntegerField()),
                ('valid_email', models.BooleanField(default=False)),
                ('fraud', models.BooleanField(default=False)),
            ],
        ),
    ]
