# Generated by Django 4.1 on 2022-08-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_email_id_alter_email_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='email_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='user_phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
