# Generated by Django 4.1 on 2022-08-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_email_email_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='email_status',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='fraud',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
